// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeDocument(arg1) {
  return window['go']['main']['App']['AnalyzeDocument'](arg1);
}

export function ApproveMessage(arg1) {
  return window['go']['main']['App']['ApproveMessage'](arg1);
}

export function DeleteAutoApprovalRule(arg1) {
  return window['go']['main']['App']['DeleteAutoApprovalRule'](arg1);
}

export function GetAllCategories() {
  return window['go']['main']['App']['GetAllCategories']();
}

export function GetAllConfig() {
  return window['go']['main']['App']['GetAllConfig']();
}

export function GetAutoApprovalRules() {
  return window['go']['main']['App']['GetAutoApprovalRules']();
}

export function GetMessageDetail(arg1) {
  return window['go']['main']['App']['GetMessageDetail'](arg1);
}

export function GetNextSteps(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetNextSteps'](arg1, arg2, arg3);
}

export function GetOwnedCategories() {
  return window['go']['main']['App']['GetOwnedCategories']();
}

export function GetPendingMessages() {
  return window['go']['main']['App']['GetPendingMessages']();
}

export function GetProcessedMessages(arg1) {
  return window['go']['main']['App']['GetProcessedMessages'](arg1);
}

export function GetSlackStatus() {
  return window['go']['main']['App']['GetSlackStatus']();
}

export function HasCustomCategories() {
  return window['go']['main']['App']['HasCustomCategories']();
}

export function IsMonitoring() {
  return window['go']['main']['App']['IsMonitoring']();
}

export function IsSetupComplete() {
  return window['go']['main']['App']['IsSetupComplete']();
}

export function IsSlackConnected() {
  return window['go']['main']['App']['IsSlackConnected']();
}

export function ListSlackChannels() {
  return window['go']['main']['App']['ListSlackChannels']();
}

export function PreloadMentionTargets() {
  return window['go']['main']['App']['PreloadMentionTargets']();
}

export function QueueMessage(arg1) {
  return window['go']['main']['App']['QueueMessage'](arg1);
}

export function ReconnectSlack() {
  return window['go']['main']['App']['ReconnectSlack']();
}

export function RefreshSlackToken() {
  return window['go']['main']['App']['RefreshSlackToken']();
}

export function RejectMessage(arg1) {
  return window['go']['main']['App']['RejectMessage'](arg1);
}

export function ResetToDefaultCategories() {
  return window['go']['main']['App']['ResetToDefaultCategories']();
}

export function ResolveMentionName(arg1) {
  return window['go']['main']['App']['ResolveMentionName'](arg1);
}

export function SaveAckReplyEnabled(arg1) {
  return window['go']['main']['App']['SaveAckReplyEnabled'](arg1);
}

export function SaveAnthropicKey(arg1) {
  return window['go']['main']['App']['SaveAnthropicKey'](arg1);
}

export function SaveAutoApprovalRule(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveAutoApprovalRule'](arg1, arg2, arg3);
}

export function SaveConfidenceThreshold(arg1) {
  return window['go']['main']['App']['SaveConfidenceThreshold'](arg1);
}

export function SaveCustomCategories(arg1) {
  return window['go']['main']['App']['SaveCustomCategories'](arg1);
}

export function SaveOwnedCategories(arg1) {
  return window['go']['main']['App']['SaveOwnedCategories'](arg1);
}

export function SaveSquadConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSquadConfig'](arg1, arg2, arg3);
}

export function SaveWatchChannel(arg1) {
  return window['go']['main']['App']['SaveWatchChannel'](arg1);
}

export function SearchMentionTargets(arg1, arg2) {
  return window['go']['main']['App']['SearchMentionTargets'](arg1, arg2);
}

export function StartMonitoring() {
  return window['go']['main']['App']['StartMonitoring']();
}

export function StopMonitoring() {
  return window['go']['main']['App']['StopMonitoring']();
}

export function TestNotification() {
  return window['go']['main']['App']['TestNotification']();
}

export function TestTriageChannel(arg1) {
  return window['go']['main']['App']['TestTriageChannel'](arg1);
}

export function TestWatchChannel(arg1) {
  return window['go']['main']['App']['TestWatchChannel'](arg1);
}

export function UnrouteMessage(arg1) {
  return window['go']['main']['App']['UnrouteMessage'](arg1);
}
