// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {classifier} from '../models';
import {db} from '../models';
import {slack} from '../models';

export function AnalyzeDocument(arg1:string):Promise<Array<classifier.ExtractedCategory>>;

export function ApproveMessage(arg1:string):Promise<void>;

export function DeleteAutoApprovalRule(arg1:number):Promise<void>;

export function GetAllCategories():Promise<Array<classifier.Category>>;

export function GetAllConfig():Promise<Record<string, string>>;

export function GetAutoApprovalRules():Promise<Array<db.AutoApprovalRule>>;

export function GetOwnedCategories():Promise<Record<string, string>>;

export function GetPendingMessages():Promise<Array<db.ProcessedMessage>>;

export function GetProcessedMessages(arg1:number):Promise<Array<db.ProcessedMessage>>;

export function GetSlackStatus():Promise<Record<string, string>>;

export function HasCustomCategories():Promise<boolean>;

export function IsMonitoring():Promise<boolean>;

export function IsSetupComplete():Promise<boolean>;

export function IsSlackConnected():Promise<boolean>;

export function ListSlackChannels():Promise<Array<slack.ChannelInfo>>;

export function QueueMessage(arg1:string):Promise<void>;

export function ReconnectSlack():Promise<string>;

export function RejectMessage(arg1:string):Promise<void>;

export function ResetToDefaultCategories():Promise<void>;

export function SaveAnthropicKey(arg1:string):Promise<void>;

export function SaveAutoApprovalRule(arg1:string,arg2:number,arg3:boolean):Promise<void>;

export function SaveConfidenceThreshold(arg1:string):Promise<void>;

export function SaveCustomCategories(arg1:Array<Record<string, string>>):Promise<void>;

export function SaveOwnedCategories(arg1:Record<string, string>):Promise<void>;

export function SaveSquadConfig(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveWatchChannel(arg1:string):Promise<void>;

export function StartMonitoring():Promise<void>;

export function StopMonitoring():Promise<void>;

export function TestTriageChannel(arg1:string):Promise<string>;

export function TestWatchChannel(arg1:string):Promise<string>;

export function UnrouteMessage(arg1:string):Promise<void>;
