// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectSlack() {
  return window['go']['main']['App']['ConnectSlack']();
}

export function GetAllCategories() {
  return window['go']['main']['App']['GetAllCategories']();
}

export function GetAllConfig() {
  return window['go']['main']['App']['GetAllConfig']();
}

export function GetOwnedCategories() {
  return window['go']['main']['App']['GetOwnedCategories']();
}

export function GetProcessedMessages(arg1) {
  return window['go']['main']['App']['GetProcessedMessages'](arg1);
}

export function GetSlackAuthURL() {
  return window['go']['main']['App']['GetSlackAuthURL']();
}

export function IsMonitoring() {
  return window['go']['main']['App']['IsMonitoring']();
}

export function IsSetupComplete() {
  return window['go']['main']['App']['IsSetupComplete']();
}

export function IsSlackConnected() {
  return window['go']['main']['App']['IsSlackConnected']();
}

export function ListSlackChannels() {
  return window['go']['main']['App']['ListSlackChannels']();
}

export function SaveAnthropicKey(arg1) {
  return window['go']['main']['App']['SaveAnthropicKey'](arg1);
}

export function SaveConfidenceThreshold(arg1) {
  return window['go']['main']['App']['SaveConfidenceThreshold'](arg1);
}

export function SaveOwnedCategories(arg1) {
  return window['go']['main']['App']['SaveOwnedCategories'](arg1);
}

export function SaveSquadConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSquadConfig'](arg1, arg2, arg3);
}

export function SaveWatchChannel(arg1) {
  return window['go']['main']['App']['SaveWatchChannel'](arg1);
}

export function StartMonitoring() {
  return window['go']['main']['App']['StartMonitoring']();
}

export function StopMonitoring() {
  return window['go']['main']['App']['StopMonitoring']();
}
