// This file is automatically generated. DO NOT EDIT

export function GetAllCategories(): Promise<Array<{Key: string, Name: string, Description: string}>>;
export function GetAllConfig(): Promise<{[key: string]: string}>;
export function GetOwnedCategories(): Promise<{[key: string]: string}>;
export function GetProcessedMessages(limit: number): Promise<Array<any>>;
export function IsMonitoring(): Promise<boolean>;
export function IsSetupComplete(): Promise<boolean>;
export function ListSlackChannels(): Promise<Array<{id: string, name: string}>>;
export function SaveAnthropicKey(key: string): Promise<void>;
export function SaveConfidenceThreshold(threshold: string): Promise<void>;
export function SaveOwnedCategories(categories: {[key: string]: string}): Promise<void>;
export function SaveSlackTokens(botToken: string, appToken: string): Promise<string>;
export function SaveSquadConfig(squadName: string, pingGroup: string, triageChannelID: string): Promise<void>;
export function SaveWatchChannel(channelID: string): Promise<void>;
export function StartMonitoring(): Promise<void>;
export function StopMonitoring(): Promise<void>;
