// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {classifier} from '../models';
import {db} from '../models';
import {slack} from '../models';

export function ConnectSlack(arg1:string,arg2:string):Promise<string>;

export function GetAllCategories():Promise<Array<classifier.Category>>;

export function GetAllConfig():Promise<Record<string, string>>;

export function GetOwnedCategories():Promise<Record<string, string>>;

export function GetProcessedMessages(arg1:number):Promise<Array<db.ProcessedMessage>>;

export function IsMonitoring():Promise<boolean>;

export function IsSetupComplete():Promise<boolean>;

export function ListSlackChannels():Promise<Array<slack.ChannelInfo>>;

export function SaveAnthropicKey(arg1:string):Promise<void>;

export function SaveConfidenceThreshold(arg1:string):Promise<void>;

export function SaveOwnedCategories(arg1:Record<string, string>):Promise<void>;

export function SaveSlackToken(arg1:string):Promise<string>;

export function SaveSquadConfig(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveWatchChannel(arg1:string):Promise<void>;

export function StartMonitoring():Promise<void>;

export function StopMonitoring():Promise<void>;
